# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Universal CPA Review
email: info@universalcpareview.com
author: Universal CPA Review
description: >
  Pass the CPA on the first try. More effective than simple books. Try it now.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.universalcpareview.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/logo.png
permalink: pretty

collections:
  products:
    output: true
  reviews:
    output: false
  team:
    output: false
  faqs:
    output: false
  positions:
    output: false

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product

jekyll_timeago:
  depth: 2

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-timeago

exclude:
  - Gemfile
  - Gemfile.lock
  - venv
  - circle.yml
  - vendor
  - node_modules