---

- name: Ensure builds directory exists
  file: path=/var/www/html/builds state=directory mode=0755

- name: Copy _site to remote tmp directory
  synchronize: src=_site dest=/tmp/build

- name: Copy remote build to builds directory
  command: rsync -rv --exclude=.git /tmp/build/_site/ /var/www/html/builds/{{ build }}

- name: Hot load new build
  file: src=/var/www/html/builds/{{ build }} dest=/var/www/html/{{ site_name }} state=link force=yes

