---

- name: Upload Build To S3
  command: aws s3 sync _site s3://{{ bucket }}/{{ build }}

- name: Move build live
  command: aws s3 sync s3://{{ bucket }}/{{ build }} s3://{{ bucket }}

- name: Invalidate CF
  command: aws cloudfront create-invalidation --distribution-id {{ cloudfront_distribution }} --paths "/*"
