---
hide_body: false
is_partial: false
fields:
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: product
- type: textarea
  label: Short Description
  name: short_description
  description: Renders to the short description
  config:
    required: true
pages:
- _products/bec.md
- _products/aud.md
- _products/far.md
- _products/reg.md
