---
hide_body: false
is_partial: false
fields:
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: product
- type: textarea
  label: Short Description
  name: short_description
  description: Renders to the short description
  config:
    required: true
- type: field_group_list
  label: Features
  name: features
  description: The features unique to this product
  fields:
  - type: text
    name: feature
    label: Feature
    description: A single feature
  config:
    labelField: feature
pages:
- _products/bec.md
- _products/aud.md
- _products/far.md
- _products/reg.md
