---
label: products
hide_body: false
is_partial: false
fields:
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: product
- type: textarea
  label: Short Description
  name: short_description
  description: Renders to the short description
  config:
    required: true
- type: list
  default: []
  label: Features
  name: features
  config:
    use_select: false
    source:
      type: datafiles
  description: ''
- type: text
  name: price
  label: Price
  description: The price to display for the product
- type: text
  name: old_price
  label: Old Price
  description: If you want to show a crossed out "original price", set this value
- type: field_group
  name: featured_bundle
  label: Featured Bundle
  description: A bundle to feature on the page
  fields:
  - type: text
    name: header
    label: Header
    description: The featured bundle section header
  - type: textarea
    name: subheader
    label: Subheader
    description: The featured bundle section subheader
  - type: text
    name: name
    label: Name
    description: The name of the Product Bundle (for instance 'Practice Test and eBook')
  - type: field_group_list
    name: images
    label: Images
    description: List of images representing the items in the bundle
    config:
      max: '4'
    fields:
    - type: file
      name: image
      label: Image
  - type: text
    label: CTA Text
    name: cta_text
    description: The text of the CTA button in the Featured Bundle section
  - type: text
    name: checkout_code
    label: Checkout Code
    description: The shortcode of the product bundle. Needs to match the shortcode
      set in the app Admin exactly
- type: field_group
  name: ebook
  label: Ebook
  description: EBook associated with this product
  fields:
  - type: text
    label: Checkout Code
    name: checkout_code
    description: The checkout code for the ebook
  - type: text
    name: price
    label: Price
    description: The price for the ebook (like "$99")
- type: field_group
  name: section_video
  label: Section Video
  description: The video section (if desired)
  fields:
  - type: text
    name: header
    label: Header
    description: The header for the section
  - type: text
    name: subheader
    label: Subheader
    description: the video section subheader (if desired)
  - type: text
    label: yt_id
    name: yt_id
    description: The YouTube ID of the video to embed
pages:
- _products/bec.md
- _products/aud.md
- _products/reg.md
- _products/far.md
